In [2]:

import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv(r'moods_preprocessed.csv')
dataset= pd.DataFrame(data)
dataset.head()

,Unnamed: 0,tempo,instrumentalness,acousticness,energy,valence,loudness,mood
0,0,118.523,0.000000,0.13700,0.730,0.625,0.779912,Happy
1,1,120.255,0.196000,0.01890,0.832,0.166,0.852145,Sad
2,2,136.168,0.000077,0.91300,0.139,0.116,0.615590,Sad
3,3,193.100,0.000006,0.08900,0.438,0.587,0.672509,Happy
4,4,169.881,0.000000,0.00171,0.932,0.445,0.885932,Energetic

In [3]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns


dataset['mood']=dataset['mood'].map({'Happy':0, 'Sad':1, 'Energetic': 2, 'Calm':3 }).astype(int)
dataset.head()

,Unnamed: 0,tempo,instrumentalness,acousticness,energy,valence,loudness,mood
0,0,118.523,0.000000,0.13700,0.730,0.625,0.779912,0
1,1,120.255,0.196000,0.01890,0.832,0.166,0.852145,1
2,2,136.168,0.000077,0.91300,0.139,0.116,0.615590,1
3,3,193.100,0.000006,0.08900,0.438,0.587,0.672509,0
4,4,169.881,0.000000,0.00171,0.932,0.445,0.885932,2

In [4]:
data= pd.DataFrame(dataset, columns=['tempo', 'acousticness', 'instrumentalness', 'valence', 'energy', 'loudness', 'mood'])
data.head()

     tempo  acousticness  instrumentalness  valence  energy  loudness  mood
0  118.523       0.13700          0.000000    0.625   0.730  0.779912     0
1  120.255       0.01890          0.196000    0.166   0.832  0.852145     1
2  136.168       0.91300          0.000077    0.116   0.139  0.615590     1
3  193.100       0.08900          0.000006    0.587   0.438  0.672509     0
4  169.881       0.00171          0.000000    0.445   0.932  0.885932     2

In [5]:
x_data=data.drop(['mood'], axis=1)
y_data=data['mood']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data,test_size=0.25)
model=RandomForestClassifier(n_estimators=150)
model.fit(X_train,y_train)
ypred=model.predict(X_test) #These are the predicted output values

In [9]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[19  4 11  0]
 [ 4 42  1  3]
 [ 8  0 40  0]
 [ 0  1  0 39]]
Classification Report:
              precision    recall  f1-score   support

           0       0.61      0.56      0.58        34
           1       0.89      0.84      0.87        50
           2       0.77      0.83      0.80        48
           3       0.93      0.97      0.95        40

    accuracy                           0.81       172
   macro avg       0.80      0.80      0.80       172
weighted avg       0.81      0.81      0.81       172

Accuracy: 0.813953488372093